//
//  Tag.swift
//  neme
//
//  Created by surla on 9/15/26.
//

import Foundation
import SwiftData

@Model
class Tag {
    var name: String
    var isAutoGenerated: Bool
    var books: [Book] = []
    
    init(name: String, isAutoGenerated: Bool = false, books: [Book] = []) {
        self.name = name
        self.isAutoGenerated = isAutoGenerated
        self.books = books
    }
}
