//
//  TagChip.swift
//  neme
//
//  Created by surla on 9/23/26.
//

import SwiftUI

struct TagChip: View {
    let text: String
    let isAutoGenerated: Bool
    
    var body: some View {
        HStack(spacing: 4) {
            if isAutoGenerated {
                Image(systemName: "sparkles")
                    .font(.system(size: 10))
            }
            Text(text)
                .font(.caption)
        }
        .padding(.horizontal, 10)
        .padding(.vertical, 4)
        .background(isAutoGenerated ? Color(.systemGray6) : Color.accentColor.opacity(0.15))
        .foregroundStyle(isAutoGenerated ? .secondary : Color.accentColor)
        .overlay(
            Capsule().stroke(isAutoGenerated ? Color(.systemGray4) : .clear, lineWidth: 0.5)
        )
        .clipShape(Capsule())
    }

}

#Preview {
    HStack {
        TagChip(text: "Fiction", isAutoGenerated: true)
        TagChip(text: "grief", isAutoGenerated: false)
    }
}
