//
//  AddBookConfirmationView.swift
//  neme
//
//  Created by surla on 9/22/26.
//

import SwiftUI

struct AddBookConfirmationView: View {
    let result: BookSearchResult
    
    @State private var startDate = Date.now
    @State private var isAddingTag = false
    @State private var newTagText = ""
    @State private var personalTags: [String] = []
    
    var body: some View {
        VStack(spacing: 16) {
            let secureURLString = result.coverURL?.replacingOccurrences(of: "http://", with: "https://")
            AsyncImage(url: URL(string: secureURLString ?? "")) { image in
                image.resizable().aspectRatio(contentMode: .fit)
            } placeholder: {
                Image(systemName: "book.closed")
            }
            .frame(width: 120, height: 170)
            
            Text(result.title)
                .font(.title3)
                .fontWeight(.semibold)
            Text(result.authors.joined(separator: ", "))
                .foregroundStyle(.secondary)
            
            DatePicker("Started reading", selection: $startDate, displayedComponents: .date)
            
            VStack(alignment: .leading, spacing: 8) {
                Text("Tags")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                
                FlowLayout(spacing: 6) {
                    ForEach(result.categories, id: \.self) { category in
                        TagChip(text: category, isAutoGenerated: true)
                    }
                    
                    ForEach(personalTags, id: \.self) { tag in
                        TagChip(text: tag, isAutoGenerated: false)
                    }
                    
                    if isAddingTag {
                        TextField("Tag name", text: $newTagText)
                            .font(.caption)
                            .textFieldStyle(.plain)
                            .frame(width: 80)
                            .onSubmit {
                                guard !newTagText.isEmpty else { return }
                                personalTags.append(newTagText)
                                newTagText = ""
                                isAddingTag = false
                            }
                    } else {
                        Button {
                            isAddingTag = true
                        } label: {
                            HStack(spacing: 4) {
                                Image(systemName: "plus")
                                    .font(.system(size: 10))
                                Text("Add tag")
                                    .font(.caption)
                            }
                            .padding(.horizontal, 10)
                            .padding(.vertical, 4)
                            .foregroundStyle(.secondary)
                            .overlay(
                                Capsule().stroke(Color(.systemGray4), style: StrokeStyle(lineWidth: 0.5, dash: [3]))
                            )
                        }
                    }
                }
            }
            
            Button("Add this book") {
            
            }
            .buttonStyle(.borderedProminent)
        }
        
        .padding()
    }
}

#Preview {
    AddBookConfirmationView(result: BookSearchResult(
        id: "1",
        title: "The Wind-Up Bird Chronicle",
        authors: ["Haruki Murakami"],
        coverURL: nil,
        publicationYear: "1994",
        categories: ["Fiction", "Magical Realism"]
    ))
}
